### PR TITLE
Add no_std support

### PR DESCRIPTION
**Pull request by stuffmatic**
This is a first pass on `no_std` support https://github.com/AlexCharlton/midi-msg/issues/2. Some early feedback would be much appreciated.

Things remaining to do/think about include

* I've removed `impl error::Error for ParseError {}` to avoid using `std::error`, not sure if there's a better solution
* It would probably be good with some unit tests confirming that the `micromath` functions used are sufficiently accurate

### CODE REVIEW

**Comment by AlexCharlton** [comment]
It's looking pretty good to me!

It doesn't really seem like there's a great option to avoid using `std::error`. Perhaps this crate should have some feature around `no_std` where `error::Error` is implemented when it's _not_ a `no_std` build? It's a little cumbersome, but I think having the option of treating `ParseError` like an `Error` is nice to have.

Outside of the `util.rs` functions that are tested, I'm not particularly worried about the accuracy of the other math operations. The only slightly dicey non-tested op I see would be the `ln` in `GlobalParamaterControl::reverb`, but it's gettings squashed to 7 bits, so I don't think there's any way `micromath` isn't at least that accurate.

**Comment by stuffmatic** [comment]
> Perhaps this crate should have some feature around no_std where error::Error is implemented when it's not a no_std build?

I've added a "std" cargo feature to allow optional access to std APIs. Seems to be the standard approach.

> Outside of the util.rs functions that are tested, I'm not particularly worried about the accuracy of the other math operations. The only slightly dicey non-tested op I see would be the ln in GlobalParamaterControl::reverb, but it's gettings squashed to 7 bits, so I don't think there's any way micromath isn't at least that accurate.

`powf`, `log2` and `ln` seem to have maximum relative errors of [0.002](https://github.com/tarcieri/micromath/blob/main/src/float/powf.rs#L39), [0.001](https://github.com/tarcieri/micromath/blob/main/src/float/log2.rs#L16) and [0.001](https://github.com/tarcieri/micromath/blob/main/src/float/ln.rs#L52) respectively, which should be good enough for `GlobalParamaterControl::reverb`. ~~Also, the `util.rs` unit tests still pass, so it looks like `micromath` is accurate enough for our purposes~~.

Edit:

Hmm.... It looks like the unit tests use math functions from `std::f32`. When I switched to calling `micromath` functions explicitly, e.g `F32Ext::powf`, some unit test fail due to the lower precision of `micromath`.

**Comment by AlexCharlton** [comment]
> I've added a "std" cargo feature to allow optional access to std APIs. Seems to be the standard approach.

Cool. Shall we make this the default then?

> Hmm.... It looks like the unit tests use math functions from std::f32. When I switched to calling micromath functions explicitly, e.g F32Ext::powf, some unit test fail due to the lower precision of micromath.

Interesting. I wouldn't be opposed to just rewriting the tests to use the new values. The values in that test are already outside of the examples given in the spec, presumably because I used a higher precision throughout the calculations than the authors. Ultimately for float frequency -> cents, the [differences between two nearby values are imperceptible](https://en.wikipedia.org/wiki/Cent_(music)#Human_perception).

**Comment by stuffmatic** [comment]
> Cool. Shall we make this the default then?

Sounds good.

> Interesting. I wouldn't be opposed to just rewriting the tests to use the new values.

Cool. While I'm at it, maybe I should also ditch the drop in replacement math functions of `micromath` in favour of their explicit counterparts, so `F32Ext::powf(2.0, 3.0)` instead of `2.0.powf(3.0)`, to make it more obvious what's happening?

**Comment by AlexCharlton** [comment]
Nicely done!

**Pull request merged**
